export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  DASHBOARD: {
    HOME: "/dashboard",
    USERS: "/dashboard/users",
    USERS_ADD: "/dashboard/users/add",
    USERS_EDIT: "/dashboard/users/edit",
    PRODUCTS: "/dashboard/products",
    PRODUCTS_ADD: "/dashboard/products/add",
    PRODUCTS_EDIT: (id: string) => `/dashboard/products/edit/${id}`,
    CATEGORIES: "/dashboard/categories",
    CATEGORIES_ADD: "/dashboard/categories/add",
    CATEGORIES_EDIT: "/dashboard/categories/edit",
    SUBCATEGORIES: "/dashboard/subcategories",
    SUBCATEGORIES_ADD: "/dashboard/subcategories/add",
    SUBCATEGORIES_EDIT: "/dashboard/subcategories/edit",
    BRAND: "/dashboard/brand",
    BRAND_ADD: "/dashboard/brand/add",
    BRAND_EDIT: "/dashboard/brand/edit",
    ORDERS: "/dashboard/orders",
    ORDER_DETAIL: (id: string) => `/dashboard/orders/${id}`,
  },
} as const;
